### ISSUE TITLE
Cannot test @Output() of a mocked component if @Output() is an Observable

### ISSUE THREAD

**Issue by naeemb123** [help-me-mom/ng-mocks#3266]
You can successfully test whether your component reacts to @Output events of a mocked component, when the @Output is an Event Emitter. But it doesn't work when the @Output of the mocked component is an Observable - it does not trigger an event on the parent anymore.

This works in production as @Outputs are Observables under the hood in Angular.

Consider the following code:
`<mocked-component (someOutput)="triggerSomething($event)"></mocked-component>`

This following works fine:
```
export class MockedComponent {
 @Output() onSomeChange = new EventEmitter();
}
```

This following does not work fine:
```
export class MockedComponent {
 @Output() onSomeChange = someObservable$;
}
```

**Comment by satanTime** [comment]
Hi @naeemb123, could you provide an example of a failing test?

**Comment by naeemb123** [comment]
Here's an example of a test that uses both the EventEmitter approach - which works, and the Observable approach - which doesn't work

https://stackblitz.com/edit/github-57pjuh-s4h7ws?file=src/examples/MockComponent/test.spec.ts

**Comment by satanTime** [comment]
In your example, you redefine the output observable after rending, whereas `MyComponent` is still listening to the original one.
It won't work in any scenario, even with pure `TestBed`.
I've updated your code to have the same behavior for both outputs, and, as expected, both of them are failing now: https://stackblitz.com/edit/github-57pjuh-vs5jvj?file=src%2Fexamples%2FMockComponent%2Ftest.spec.ts

To fix this, you need to substitute `testOutput$` before rendering. For example, you can do it with help of `MockInstance`:
https://stackblitz.com/edit/github-57pjuh-9c7mdj?file=src%2Fexamples%2FMockComponent%2Ftest.spec.ts

If it's been your problem, then the fix is to use `MockInstance`. Otherwise, please adjust the example to demonstrate the problem correctly.

**Comment by satanTime** [comment]
Hi @naeemb123,

I hope this finds you well.
I wanted to ask if you've had a chance to take a look at my comment above?

**Comment by satanTime** [comment]
Hi @naeemb123, any update on this?

**Comment by satanTime** [comment]
Hi @naeemb123, I'm going to close the issue. Feel free to update and reopen it when you have more info.
