### ISSUE TITLE
Bug: Arrow functions not mocked as functions 

### ISSUE THREAD

**Issue by md-idea** [help-me-mom/ng-mocks#3674]
### Description of the bug

I have a service which uses some arrow functions for binding reasons.

I'm getting an error when trying to spy on the arrow functions:
Error: <spyOn> : could not find an object to spy upon for post()
Usage: spyOn(< object>, < methodName>)

If I console.log my service instance in the spec file then I can see only the non-arrow functions in the log

### An example of the bug

You can see a different error but the same problem in one of your examples if you modify it slightly.

Open this example and the tests pass
https://codesandbox.io/s/github/help-me-mom/ng-mocks-sandbox/tree/tests?file=/src/examples/MockProvider/test.spec.ts&initialpath=%3Fspec%3DMockProvider

Change the "echo" function of Dependency1Service into an arrow function and it fails with:
TypeError: fixture.point.injector.get(...).echo is not a function

### Expected vs actual behavior

I'd expect that all arrow functions are mocked in the same way that standard class methods/functions are mocked so that I can spy on them without having to manually mock them

**Comment by satanTime** [comment]
Hi @md-idea,

thanks for the report, however the problem here isn't in `ng-mock` but in `typescript`.
Arrow functions aren't the part of the prototype of their classes. They are created in constructors, and it means that in a mock class it's impossible to detect them.
Check how arrow function is generated in a class: https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiCmAHeA7AJq4BPATAZXgCcA3AS2HmgG8AoaaRAVwCMRzoUwBbSgXmgBEAFzCEA5vCECA3DTrR4wABYB7aPwAUASgBc0CEMKkUY9QD5q8+oUmNCKaEKWkIAOk49Z9AL6zvQA
Check how a proper method is generated in a class: https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiCmAHeA7AJq4BPATAZXgCcA3AS2HmgG8AoaaRAVwCMRzoUwBbSgXmgBEAFzCEA5vCECA3DTrR4wABYB7ABQBKAFzQIQwqRRjq8+oUmNCKaEKWkIAOk49Z9AL403QA

`ng-mocks` provides [`ngMocks.defaultMock`](https://ng-mocks.sudo.eu/api/ngMocks/defaultMock) which can help to define a spy on the `echo` property. This is the updated example of the test: https://codesandbox.io/s/empty-monad-2oewki?file=/src/examples/MockProvider/test.spec.ts:562-766

I hope this helps. Please let me know if you wanted to discuss it deeper.
