### ISSUE TITLE
Default mock of MatTooltip breaks tests in Angular14

### ISSUE THREAD

**Issue by craigsnyders** [help-me-mom/ng-mocks#4168]
See https://github.com/angular/components/issues/25563

There is a comment that seems to indicate that the default MatTooltip mock causes the issue.

For my own project, to fix my tests, I have had to `.keep(MatTooltipModule)` as a workaround

**Comment by satanTime** [comment]
Hi @craigsnyders,

Thanks for the report.

Could you share a min repo with the issue?

**Comment by satanTime** [comment]
I've tried an example with `MatTooltipModule`, but it doesn't look like the problem: https://codesandbox.io/s/elastic-wildflower-uovnk0?file=/src/test.spec.ts

**Comment by satanTime** [comment]
Hi @Chris2fourlaw, @KasimJasarevic,

could you help me to reproduce the issue?

**Comment by satanTime** [comment]
For I've found so far is that this can be caused by importing `MatCommonModule` and/or `A11yModule`.
Do you use any of those?

If yes, to get the failure, they shouldn't be mocked. Is there a reason why you don't mock them?

Basically, the solution here is to `.keep(NG_MOCKS_ROOT_PROVIDERS)` or `.keep(BreakpointObserver)`, in this case, `BreakpointObserver` won't be mocked and won't cause the issue.

If you want to mock `BreakpointObserver`, then you need to stub its `.observe()`:

```ts
ngMocks.defaultMock(BreakpointObserver, () => ({
  observe: jasmine.createSpy().and.returnValue(EMPTY)
}));
```

Here is the updated test: https://codesandbox.io/s/elastic-wildflower-uovnk0?file=/src/test.spec.ts

Feel free to reopen the issue if the fix doesn't work for you.
