### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by famzila** [help-me-mom/ng-mocks#6028]
### Description of the bug

When I mock params of ActivatedRoute in Angular app, it's not working with MockInstance with `forChild` in my feature module. The `forRoot` should be used once in the root module (AppModule).

```
@NgModule({
  declarations: [CmpToTestComponent],
  imports: [RouterModule.forChild(
         {
            path: 'a-path',
            component: CmpToTestComponent,
          },
  )],
 ....
})
export class FeatureModule {}
```

### An example of the bug

Link: https://stackblitz.com/edit/github-2gay9u-vhgon8?file=src%2Ftest.spec.ts

### Expected vs actual behavior

**Expected:**
Be able to use MockInstance with feature module where any route is added with 

```
RouterModule.forChild([
      {
        path: 'test/:paramId',
        component: TargetComponent,
      },
    ]),
```

**Actual behavior:**
Test works only when I use 
```
RouterModule.forRoot([
      {
        path: 'test/:paramId',
        component: TargetComponent,
      },
    ]),
```

In Angular we use `forRoot` only for the root Module `AppModule`

**Comment by satanTime** [comment]
Hi @famzila,

thanks for reporting the issue.

However, the problem is there how `ActivatedRoute` is provided, and it's provided by `RouterModule`.
In your case, it means you need to mock the module which imports `RouterModule` or `RouterModule` itself:

```ts
beforeEach(() => MockBuilder(TargetComponent, [TargetModule, RouterModule.forRoot([])]));
```

this solves the issue.

Feel free to comment or reopen the issue if anything should be clarified further.
