### ISSUE TITLE
Bug: Overwriting defaultMock of 'get' or readonly property results in `Property ... does not have access type get`

### ISSUE THREAD

**Issue by atharkes** [help-me-mom/ng-mocks#6657]
### Description of the bug
Mocking a get-only property with a `defaultMock` seems to remove the fact that it is a get-only property. As later overwriting it using `spyOnProperty` gives the error: Property ... does not have access type get.

### An example of the bug
```
// Service to mock
class SomeService {
  readonly someObservable$: Observable<{}> = of({});
  // Or
  get someObservable$(): Observable<{}> {
    return of({})
  }
}

// test.ts
ngMocks.defaultMock(SomeService, () => ({
  someObservable$: EMPTY,
}));

// In a spec file
beforeEach(async () => {
  await MockBuilder(SomeComponent, AppModule);
  fixture = MockRender(SomeComponent, {});
  sut = fixture.point.componentInstance;
});

const someService = TestBed.inject(SomeService) as jasmine.SpyObj<SomeService>;
const item = {};
spyOnProperty(someService, 'someObservable$').and.returnValue(of([item]));
```

### Expected vs actual behavior
Expected: overwrite the default mock return value with a new return value.
Actual: Error `Property someObservable$ does not have access type get`

**Comment by satanTime** [comment]
Hi @atharkes,

this is expected, because what you defined as a mock doesn't have getter or setter anymore, and it's the same as to do:

```ts
    spyOnProperty({
      someObservable$: EMPTY,
    }, 'someObservable$').and.returnValue(of({}));
```
which also fails with `<spyOnProperty> : Property someObservable$ does not have access type get`.


To change a normal property to become a getter / setter again, you need to use [`ngMocks.stubMember`](https://ng-mocks.sudo.eu/api/ngMocks/stubMember):

```ts
ngMocks.stubMember(someService, 'someObservable$', jasmine.createSpy(), 'get').and.returnValue(of({}));
```

It will redefine `someObservable$` as a getter which calls the spy.

**Comment by satanTime** [comment]
Or you can do 

```ts
ngMocks.defaultMock(SomeService, () => ({
  get someObservable$() {
    return EMPTY;
  },
}));
```
